// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OverReacted.Infrastructure.Persistance;

#nullable disable

namespace OverReacted.Infrastructure.Migrations
{
    [DbContext(typeof(OverReactedDbContext))]
    [Migration("20220716080102_SeedDataForRoleAndChangeFieldOnUserTable")]
    partial class SeedDataForRoleAndChangeFieldOnUserTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OverReacted.Domain.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOnUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimationReadTime")
                        .HasColumnType("integer");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedOnUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6028cde4-367b-46d4-8d70-79f83c7e1846"),
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            CreatedOnUTC = new DateTimeOffset(new DateTime(2022, 7, 16, 8, 1, 1, 729, DateTimeKind.Unspecified).AddTicks(9647), new TimeSpan(0, 0, 0, 0, 0)),
                            EstimationReadTime = 14,
                            ShortDescription = "Found 99 vulnerabilities (84 moderately irrelevant, 15 highly irrelevant)",
                            Title = "npm audit: Broken by Design",
                            UserId = new Guid("fbdceb4a-29c8-4cc2-b3f6-5ed60658f661")
                        },
                        new
                        {
                            Id = new Guid("fc0ac3e3-96ef-4f3d-adbb-8ba040844e09"),
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            CreatedOnUTC = new DateTimeOffset(new DateTime(2022, 7, 16, 8, 1, 1, 729, DateTimeKind.Unspecified).AddTicks(9652), new TimeSpan(0, 0, 0, 0, 0)),
                            EstimationReadTime = 5,
                            ShortDescription = "Rendering optimizations that come naturally.",
                            Title = "Before You memo()",
                            UserId = new Guid("fbdceb4a-29c8-4cc2-b3f6-5ed60658f661")
                        },
                        new
                        {
                            Id = new Guid("0880877d-d485-4c2e-9015-da06ccb6f065"),
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            CreatedOnUTC = new DateTimeOffset(new DateTime(2022, 7, 16, 8, 1, 1, 729, DateTimeKind.Unspecified).AddTicks(9737), new TimeSpan(0, 0, 0, 0, 0)),
                            EstimationReadTime = 5,
                            ShortDescription = "Come waste your time with me.",
                            Title = "The WET Codebase",
                            UserId = new Guid("fbdceb4a-29c8-4cc2-b3f6-5ed60658f661")
                        },
                        new
                        {
                            Id = new Guid("64aad55d-7e79-4abc-9641-02e155d5fbe4"),
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            CreatedOnUTC = new DateTimeOffset(new DateTime(2022, 7, 16, 8, 1, 1, 729, DateTimeKind.Unspecified).AddTicks(9739), new TimeSpan(0, 0, 0, 0, 0)),
                            EstimationReadTime = 5,
                            ShortDescription = "Let clean code guide you. Then let it go.",
                            Title = "Goodbye, Clean Code",
                            UserId = new Guid("fbdceb4a-29c8-4cc2-b3f6-5ed60658f661")
                        },
                        new
                        {
                            Id = new Guid("8d83f709-6d82-406e-a9ac-5f532519c983"),
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            CreatedOnUTC = new DateTimeOffset(new DateTime(2022, 7, 16, 8, 1, 1, 729, DateTimeKind.Unspecified).AddTicks(9753), new TimeSpan(0, 0, 0, 0, 0)),
                            EstimationReadTime = 26,
                            ShortDescription = "A personal reflection.",
                            Title = "My Decade in Review",
                            UserId = new Guid("fbdceb4a-29c8-4cc2-b3f6-5ed60658f661")
                        });
                });

            modelBuilder.Entity("OverReacted.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedOnUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedOnUTC")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOnUTC = new DateTimeOffset(new DateTime(2022, 7, 16, 8, 1, 1, 729, DateTimeKind.Unspecified).AddTicks(8419), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Authenticated"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOnUTC = new DateTimeOffset(new DateTime(2022, 7, 16, 8, 1, 1, 729, DateTimeKind.Unspecified).AddTicks(8423), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Author"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOnUTC = new DateTimeOffset(new DateTime(2022, 7, 16, 8, 1, 1, 729, DateTimeKind.Unspecified).AddTicks(8424), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "God"
                        });
                });

            modelBuilder.Entity("OverReacted.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOnUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastVerificationSent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedOnUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerifyCode")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fbdceb4a-29c8-4cc2-b3f6-5ed60658f661"),
                            Avatar = "https://miro.medium.com/max/3150/1*xxVEfOOAmIKHWOUloRKLhw.jpeg",
                            CreatedOnUTC = new DateTimeOffset(new DateTime(2022, 7, 16, 8, 1, 1, 729, DateTimeKind.Unspecified).AddTicks(8570), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Dan.Abramov@Facebook.com",
                            IsActive = true,
                            IsEmailActive = true,
                            LastVerificationSent = new DateTimeOffset(new DateTime(2022, 7, 16, 8, 1, 1, 729, DateTimeKind.Unspecified).AddTicks(9582), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Dan Abramov",
                            Password = "73l8gRjwLftklgfdXT+MdiMEjJwGPVMsyVxe16iYpk8=",
                            RoleId = 2,
                            VerifyCode = "45c167842a224854ae9ac2780074891f"
                        });
                });

            modelBuilder.Entity("OverReacted.Domain.Entities.Article", b =>
                {
                    b.HasOne("OverReacted.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("OverReacted.Domain.Entities.User", b =>
                {
                    b.HasOne("OverReacted.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OverReacted.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
